name: env
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  envied: ^1.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.15
  envied_generator: ^1.1.1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0
